// setup
import './$set';
import './$vec';
import './$text';
import './$bool';
import './$binary';
import './$id';
import './$order';
import './$isNaN';
import './$isZero';
import './$normalize';
import './$concat';
import './$log';
import './$clean';
import './regex';
import './$partition';
import './$map';
import './$test';
import './$toDate';
