services:
  base:
    restart: always
    build:
      context: .
      dockerfile: client.dockerfile
    ports:
      - 9083:80

  connector-api:
    restart: always
    build:
      context: ./services/connector
      dockerfile: Dockerfile

  prediction-api:
    restart: always
    build:
      context: ./services/prediction
      dockerfile: Dockerfile

  causal-api:
    restart: always
    ports:
      - 9084:8000
    build:
      context: ./services/causal-service
      dockerfile: Dockerfile

  narrative-api:
    restart: always
    build:
      context: ./services/narrative-service
      dockerfile: Dockerfile

  text-pattern-api:
    restart: always
    build:
      context: ./services/text-pattern-service
      dockerfile: Dockerfile
