CREATE TABLE IF NOT EXISTS datasets.sales
(
    `order_id` Int64,
    `order_date` Date,
    `status` String,
    `item_id` Float64,
    `sku` String,
    `qty_ordered` Float64,
    `price` Float64,
    `value` Float64,
    `discount_amount` Float64,
    `total` Float64,
    `category` String,
    `payment_method` String,
    `bi_st` String,
    `cust_id` Float64,
    `year` String,
    `month` String,
    `ref_num` Int64,
    `Name_Prefix` String,
    `First_Name` String,
    `Middle_Initial` String,
    `Last_Name` String,
    `Gender` String,
    `age` Float64,
    `full_name` String,
    `E_Mail` String,
    `SSN` String,
    `Phone_No` String,
    `Place_Name` String,
    `County` String,
    `City` String,
    `State` String,
    `Zip` String,
    `Region` String,
    `User_Name` String,
    `Discount_Percent` Float64
) ENGINE = MergeTree ORDER BY (`order_id`, `order_date`);