server {
    listen       80;
    server_name  localhost;

    location / {
        root   /usr/share/nginx/html;
        index  index.html index.htm;
    }

    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    location /connector/api {
      proxy_pass http://localhost:5001/api;
    }

    location /api/train_test {
      proxy_pass http://localhost:5534/api/train_test;
    }

    location /api/text_pattern_extraction {
      proxy_pass http://localhost:5533/api/text_pattern_extraction;
    }

    location /insight {
      proxy_pass http://localhost:8001/insight;
    }

    location /algo/ {
      proxy_pass http://localhost:8000;
    }

    location /causal/ {
      proxy_pass http://localhost:8000;
    }

    location /explain {
      proxy_pass http://localhost:8000/explain;
    }

}