name: prod publish
on:
  push:
    branches: [master]
jobs:
  auto-build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: yarn install
      - run: yarn workspace rath-client build
      - uses: manyuanrong/setup-ossutil@master
        with:
          endpoint: ${{ secrets.ALIOSS_ENDPOINT }}
          access-key-id: ${{ secrets.ALIOSS_ID }}
          access-key-secret: ${{ secrets.ALIOSS_SECRET }}
      - run: ossutil cp -rf ./packages/rath-client/build oss://${{ secrets.ALIOSS_BUCKET }}